### ISSUE TITLE
[1.9.4] Enderthing Chest Crash when using RFTools Builder

### ISSUE THREAD

**Issue by Mohron** [gigaherz/Enderthing#10]
Version: enderthing-1.9.4-0.6.7.jar
RFTools: rftools-1.9.4-4.63.jar, mcjtylib-1.9.4-1.9.1.jar

There is a crash I've been getting time from time when using an enderthing Ender Key Chest with the RFTools builder with quarry shape card.

[RFTools Issue](https://github.com/McJty/RFTools/issues/577)

[Crash Log 1](http://pastebin.com/Kmpjbd3G)
[Crash Log 2](http://pastebin.com/PZJxcZSx)
[Crash Log 3](http://pastebin.com/avBgWsWK)

**Comment by gigaherz** [comment]
Hmf if this happens with the 0.6.7 version, that means the backport I released today, is broken. (I wish you had posted this just a few hours ago. XD)

It also means I have no idea how it can still happen. Really sucks that it cna't detect who else was involved on the Concurrent Modification :/

**Comment by gigaherz** [comment]
I can only think of two ways in which this could possibly happen:
1. A block is being loaded as a consequence of "markDirty()", which cuases this TE to call addWeakListener()
2. A block is pushing items in its onNeighborChange, which was initiated by the TE's markDirty()

I have no idea how to fix that in a clean way.

**Comment by gigaherz** [comment]
Could you try 0.6.8 and tell me if the issue stops happening?

**Comment by gigaherz** [comment]
It has been 4 days and no reply, closing. If this still happens, just comment and I will reopen.
