### ISSUE TITLE
Placing conduits before placing Ender Key Chests will not allow access to inventory.

### ISSUE THREAD

**Issue by BootyToast** [gigaherz/Enderthing#13]
I don't know how to properly explain this, but when color coding your chests with any other color than white-white-white, if there is an EnderIO conduit already placed adjacent to where you are planning to place the chest, you are denied access to automate input and extraction. Instead the color coded chest will default to the main white-white-white color coding. I've also noticed that when exiting and entering the world, the game actually thinks a color coded chest is a white-white-white until you break it.

**Comment by gigaherz** [comment]
Hmm that's annoying. What version of the mod, and version of mc/forge? I'll take a look later this afternoon when I get back from work.

**Comment by BootyToast** [comment]
Awesome, thank you! Enderthing 1.9.4-0.6.8 and Forge 12.18.0.2009

**Comment by gigaherz** [comment]
I found a visual glitch where it wouldn't properly sync/refresh the wool colors, but it shouldn't affect the ability of other mods to see and extract from it, since the issue was only client-server sync... still looking, though. I haven't installed EnderIO yet. ;P

**Comment by gigaherz** [comment]
I can't seem to be able to use EnderIO on the development environment, so I don't know how to troubleshoot this issue. I'll keep digging.

**Comment by BootyToast** [comment]
Okay! I'll try later to reproduce it. Thanks for looking into it though.

**Comment by gigaherz** [comment]
Oh I can reproduce the issue, I just can't figure out the cause yet. Something is going VERY wrong, when the chest is placed on top of an existing conduit, just I haven't been able to run it in an environment where I can step line by line and see the memory contents. ;P

**Comment by gigaherz** [comment]
I found the issue. I'm producing a fix, and will upload in a bit.

**Comment by gigaherz** [comment]
v0.6.10 should fix the issue, have fun!

**Comment by BootyToast** [comment]
Thanks a bunch!
