### ISSUE TITLE
[Bug] 1.10.2-0.6.10 - Dupe of chest with silk touch break

### ISSUE THREAD

**Issue by ingie** [gigaherz/Enderthing#15]
I'm using 0.6.10, but looking at the recent commit to Thorgal's crash issue, you haven't changed anything to fix this in 0.6.11.

When breaking a locked chest with a silk touch - so that I don't lose the chest/lock - I get a duplicated chest [and lock] if the broken chest is above a hopper... specifically the hopper takes 1 copy, I get the other :)

Initially I didn't notice why, but on testing it seems only when it's above a hopper... but since it's _normal_ to put it above a hopper I guess it's important ... I'm now up to 6 chests as I kept changing my mind as to where best to put it :)

**Comment by gigaherz** [comment]
Interesting... I will take a look when I get home from work.

**Comment by ingie** [comment]
update: it may not be your fault actually :) I just noted that I had my "magnet" turned on, in this instance the quantum flux magnet... which does a very fast pull... i just tried without it enabled and there's no dupe... I also tried with the much slower pulling Actually Additions magnet, and that didn't dupe either... so my guess is that it might be jotato's problem :) 

but I haven't tried with other magnets as yet to see if it's just the timing. I'll report back if I find anything definitive

**Comment by ingie** [comment]
nah, you can defo let yourself off :) it's jotato's magnet... it just duped some grass for me using the same method.  sorry for worrying you, if you were at all worried. 

once i knew this, i then found this... so: 
https://github.com/joekaiser/QuantumFlux/issues/102
