### ISSUE TITLE
Disappearing Private Ender Pack

### ISSUE THREAD

**Issue by Ravin890** [gigaherz/Enderthing#18]
For some reason whenever I  attempt to make the ender pack into a private version, it disappears in the output slot. Don't know if there is some config or anything that i am missing.
Using version 0.7.1 and forge 2166

**Comment by gigaherz** [comment]
Hmm I somehow missed the notification for this issue...

I'm trying to figure this out, but I can't seem to be able to reproduce the problem. Did you have other mods installed that could possibly interfere with the recipes?

**Comment by Ravin890** [comment]
Nope. I will try and retest today and see if i can reproduce issue.

**Comment by gigaherz** [comment]
v0.7.3 MAY fix this issue. I'm not 100% sure on it, but it may. Reopen if I'm wrong.
