### ISSUE TITLE
NPE when Crafting

### ISSUE THREAD

**Issue by Towsty** [gigaherz/Enderthing#2]
Got this crash when crafting in the storage network mods Request Table. Basically I was actually crafting a capacitor from enderio which uses 4 gold nuggets as part of its recipe. 
## Crafting Pattern:

X O X
O X O
X O X

X=Empty slot in crafting gui
O = gold nugget

Crash looks like its from EnderThing, not sure why though. I did not see are recipe from your mod that was just 4 gold nuggets.

Crash Report
http://pastebin.com/ae3F43v2

**Comment by gigaherz** [comment]
I'll take a look, thanks for the report.

**Comment by gigaherz** [comment]
Found the issue. My bad. v0.5.2 coming in a few minutes.

**Comment by Towsty** [comment]
Great! Thanks!

**Comment by gigaherz** [comment]
Should work now: https://github.com/gigaherz/Enderthing/releases
Curseforge coming in a few minutes, after they review the binaries.

**Comment by Towsty** [comment]
Yep, no more crash. Thanks a bunch
