### ISSUE TITLE
Waterloggable Enderchests

### ISSUE THREAD

**Issue by WenXin20** [gigaherz/Enderthing#20]
`Minecraft v1.15.2`
`Forge v31.2.19`
`Enderthing v1.0.0`

Ender Chests in Minecraft can be waterlogged, but once converted into a Key Chest, it loses that property. Can this be added?

Also, an opening animation seems to be missing.

**Comment by gigaherz** [comment]
Ah yes. That's what I get for rushing a release so I'm not in the middle of porting when 1.16 drops. I forget things.
Thanks for reminding me. :)

**Comment by gigaherz** [comment]
Fixed as of v1.0.1
Enjoy!
And thanks again for reporting. So many people tend to just either assume someone else must have reported, or just shrug and walk away... it's nice to get a bug report within 24 hours of release. XD

**Comment by WenXin20** [comment]
Thanks for the quick fix!
