### ISSUE TITLE
Hard crash when linked to any storage mod

### ISSUE THREAD

**Issue by joacmc** [gigaherz/Enderthing#23]
The ender chests from this mod are incompatible with any of the storage mods I've tried (Simple Storage Network, Pretty Pipes).
Linking the chest to the system causes the game to crash.
On server removing the storage mod allows the map to work again.
On single player I have not found a way to recover a map once it crashes.

To reproduce:

1. Launch game with Enderthings, any required files and either Simple Storage or Prettypipes.
2. Set up the storage mod
3. Connect with cable to an Enderthings locked enderchest.

[2020-10-23-2.log.gz](https://github.com/gigaherz/Enderthing/files/5431560/2020-10-23-2.log.gz)

**Comment by gigaherz** [comment]
The log doesn't show any indication that it's my mod doing the crashing. It seems to error inside forge code:
```
Caused by: java.lang.NoSuchMethodError: net.minecraft.util.ResourceLocation.compareNamespaced(Lnet/minecraft/util/ResourceLocation;)I
	at net.minecraftforge.event.RegistryEvent$MissingMappings$Mapping.compareTo(RegistryEvent.java:238) ~[?:?]
	at net.minecraftforge.event.RegistryEvent$MissingMappings$Mapping.compareTo(RegistryEvent.java:167) ~[?:?]
	at java.util.Comparators$NaturalOrderComparator.compare(Comparators.java:52) ~[?:1.8.0_51]
	at java.util.Comparators$NaturalOrderComparator.compare(Comparators.java:47) ~[?:1.8.0_51]
	at java.util.TimSort.countRunAndMakeAscending(TimSort.java:351) ~[?:1.8.0_51]
	at java.util.TimSort.sort(TimSort.java:216) ~[?:1.8.0_51]
```
This strongly sounds like an Optifine compatibility problem. Optifine is well known to overwrite entire classes with their own patched implementation, meaning it can easily overwrite forge patches with versions that don't contain that patch. I would assume it will work just fine without optifine installed.

I'll reopen the issue if this is not the case.

**Comment by joacmc** [comment]
Tried again with just simple storage and enderthings installed, error still happens.

[latest.log](https://github.com/gigaherz/Enderthing/files/5431684/latest.log)

**Comment by gigaherz** [comment]
Aha! THAT's an Enderthing error. The other mod is trying to access the enderthing chest contents client-side, but this is not supported, I probably should return a fake empty inventory instead of crashing. :P

**Comment by gigaherz** [comment]
I'll release a workaround shortly. That said, the true issue is in Storage Network:

This piece of code: https://github.com/Lothrazar/Storage-Network/blob/trunk/1.16/src/main/java/com/lothrazar/storagenetwork/block/TileCableWithFacing.java#L47

Should read like 
```
    if (neighbor != null && neighbor.getCapability(CapabilityItemHandler.ITEM_HANDLER_CAPABILITY, facing.getOpposite()).isPresent()) {
```

You should report this problem to them: They should NOT be resolving the actual value of a capability, just to check for presence, that's why it's a **Lazy** Optional. To avoid doing that.

**Comment by gigaherz** [comment]
v1.0.4 is up on curseforge, and it should avoid the crash.
