### ISSUE TITLE
[1.21] Enderthing crash game when creating planks

### ISSUE THREAD

**Issue by Periam** [gigaherz/Enderthing#26]
Installed enderthing for MC 1.21 with neo forge, trying to create planks with the mod installed the game crash or does not create them.
In an instance with only Enderthing, the planks are not created.
In an instance with several others mod the game crash, disabling the mod the game does not crash.

Minecraft 1.21
Neo Forge 21.0.20
Enderthing-1.21-1.5.2

Crashlogs

[crash-2024-06-19_20.21.12-client.txt](https://github.com/user-attachments/files/15906612/crash-2024-06-19_20.21.12-client.txt)

**Comment by gigaherz** [comment]
Hm, it seems there's an issue with one of my recipes. I will look into it later today.
