### ISSUE TITLE
[1.9] Mouse over a bound Ender Security Card causes client crash

### ISSUE THREAD

**Issue by Melakion** [gigaherz/Enderthing#4]
enderthing-1.9-0.6.1 - Forge 1867

http://pastebin.com/ekUtVKpb

**Comment by gigaherz** [comment]
Oops. Checking...

**Comment by gigaherz** [comment]
Foudn it: I was trying to access the integrated server while on multiplayer, and it obviously isn't there.

**Comment by gigaherz** [comment]
v0.6.2 should fix your issue. A future version will have better support for displaying the correct player name in the cards. https://github.com/gigaherz/Enderthing/releases
