### ISSUE TITLE
Items in Private Packs removed after death

### ISSUE THREAD

**Issue by itayganor** [gigaherz/Enderthing#5]
Hey,
I just died on my server and i used a private ender pack to store my items.
after i died, i saw that my pack is empty.
that's a dangerous bug - i think it's super important to fix it.

minecraft version: 1.9

**Comment by gigaherz** [comment]
What version of the mod are you using? This shouldn't be a problem at all in 0.6+

**Comment by itayganor** [comment]
the name of the file is enderthing-1.9-0.5.1.jar
probably 0.5.1.

**Comment by gigaherz** [comment]
Yep, let's call it a known issue. Fix is to update the server to 0.6.4, and hope that the automatic import feature works correctly.
Note that the automatic import requires all the players to log in while the import feature is enabled, and it will turn itself off so if you want to continue importing after restarting the server, it has to be enabled again.

**Comment by itayganor** [comment]
what is automatic import feature?

**Comment by gigaherz** [comment]
While enabled, it will import the private inventories from 0.5.4 and earlier, into the format used by 0.6+, when players login to the server. It would be just too much work to import everything at once, so I wrote that, as a "less bad" alternative to not importing anything at all.

**Comment by itayganor** [comment]
and how can i enable/disable it?

**Comment by gigaherz** [comment]
It should be enabled by default the first time you start the server. If you want to enable it manually, you can use this as the contents of the "enderthing.cfg" file:

```
# Configuration file

compatibility {
    B:ImportCapabilityPrivateData=true
}
```

As soon as the server starts, it will turn itself off, and save the config, but the feature will remain enabled for the duration of the server instance, until it restarts.
