### ISSUE TITLE
Random server crash

### ISSUE THREAD

**Issue by MrJoki007** [gigaherz/Enderthing#9]
Sometimes my server crashes randomly

Now it happend when i enter the Aroma1997 mining world but my friend already in the dimension

Update: There are 4 quarrys around the enderchest

Forge version is 1902 1.8.8 and mod version is 0.6.6

[crash-2016-06-06_21.03.45-server.txt](https://github.com/gigaherz/Enderthing/files/301156/crash-2016-06-06_21.03.45-server.txt)

**Comment by gigaherz** [comment]
0.6.7 should fix this, hopefully.

**Comment by MrJoki007** [comment]
Unfortunately no version for 1.8.9 :(

**Comment by gigaherz** [comment]
I'll try to backport, howevr I'm really busy these days. I can only spare a bit on weekends.

**Comment by gigaherz** [comment]
Backports are up in the Releases tab for 1.9 and 1.8.9. Curseforge is going through review and will be up soon.
